export const Language = {
  firstName: "firstName",
  lastName: "lastName",
  email: "email",
  firstNameErrorMsg: "First name must contain only letters",
  lastNameErrorMsg: "Last name must contain only letters",
  emailErrorMsg: "Please insert a valid email address.",
  GenderErrorMsg: "Please select your Gender.",
  dateErrorMsg: "Please insert a valid date.",
  GenderLabel: "Gender",
  DateLabel: "Date of birth",
  labelName: "gender",
  male: "Male",
  female: "Female",
  Date: "DD/MM/YYYY",
  companyName: "Company name",
  select0: "-- Select --",
  select1: "Junior",
  select2: "Middle",
  select3: "Senior",
};
